"""Core primitives for Arbibot Phase 0."""

from arbibot.core.config import AppConfig, load_config
from arbibot.core.errors import (
    ArbibotError,
    ConfigError,
    EventValidationError,
    LiveTradingDisabledError,
    RiskLimitExceededError,
    StaleDataError,
    UnknownOrderStateError,
)
from arbibot.core.events import (
    BaseEvent,
    DecisionAction,
    DecisionRecord,
    ExternalSignal,
    FeatureSnapshot,
    HealthState,
    HealthStatus,
    MarketSide,
    OpportunityCandidate,
    OrderEvent,
    OrderIntent,
    OrderStatus,
    PolyBookDelta,
    PolyBookSnapshot,
    PolyTrade,
    RiskState,
    SignalDirection,
    SignalState,
    SpotBar,
    SpotTick,
)
from arbibot.core.time import event_age_ms, now_monotonic_ns, now_wall_ms, validate_timestamp_ms

__all__ = [
    "AppConfig",
    "ArbibotError",
    "BaseEvent",
    "ConfigError",
    "DecisionAction",
    "DecisionRecord",
    "EventValidationError",
    "ExternalSignal",
    "FeatureSnapshot",
    "HealthState",
    "HealthStatus",
    "LiveTradingDisabledError",
    "MarketSide",
    "OpportunityCandidate",
    "OrderEvent",
    "OrderIntent",
    "OrderStatus",
    "PolyBookDelta",
    "PolyBookSnapshot",
    "PolyTrade",
    "RiskLimitExceededError",
    "RiskState",
    "SignalDirection",
    "SignalState",
    "SpotBar",
    "SpotTick",
    "StaleDataError",
    "UnknownOrderStateError",
    "event_age_ms",
    "load_config",
    "now_monotonic_ns",
    "now_wall_ms",
    "validate_timestamp_ms",
]
